name: 'NuGet Login'
description: 'Log in to NuGet using GitHub OIDC and get a short-lived API key'

inputs:
  user:
    description: 'NuGet username'
    required: true
  token-service-url:
    description: 'Token exchange endpoint URL'
    required: false
    default: 'https://www.nuget.org/api/v2/token'
  audience:
    description: 'OIDC audience to request'
    required: false
    default: 'https://www.nuget.org'

outputs:
  NUGET_API_KEY:
    description: 'Short-lived NuGet API key'

runs:
  using: 'node16'
  main: 'dist/index.js'
